version: '3.6'
services:
  ocean-hub:
    container_name: ocean-hub
    restart: always
    env_file: .env
    build: .
    ports:
      - "9999:5005"
    #networks:
    #  - db_network
    #  - web_network
#  nginx:
#    container_name: nginx
#    restart: always
#    image: "nginx:latest"
#    ports:
#      - "80:85"
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#    networks:
#      - web_network
#    depends_on: 
#      - ocean-hub
#networks:
#  db_network:
#    driver: bridge
#  web_network:
#    driver: bridge

#networks:
#  default:
#    name: nginx_halo
#    external: true
